# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18b7536800906a5b07feb5f33ada0459d1ae28d7be88dd33237a639423faf7b5d16dca399f6f38ac8454093c5ae400482b1aa0164b3f35978f501700ce4f4423

test:
  secret_key_base: 9ec49744eb079eca0a57dbf734239802a86e1dcab874b2805e1daf6161a47e0209289b429bde392e99f9c9a53e551c1d587cbbf1a4331984aacf564b6b9e89e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
